FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["PuzzleGameAPI.csproj", "./"]
RUN dotnet restore "PuzzleGameAPI.csproj"
COPY . .
RUN dotnet build "PuzzleGameAPI.csproj" -c Release -o /app/build

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS publish
WORKDIR /src
COPY --from=build /app/build .
RUN dotnet publish "PuzzleGameAPI.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PuzzleGameAPI.dll"]
